1 psr cache
mmamedov/page-cache pull request #3
Opened 2017-04-20 14:22 UTC by spotman

Basic PSR-16 implementation done. Couple of methods was deprecated coz there is no direct access to cache file anymore. Also "headers forwarding" feature implemented so headers from application response can be stored into cache item now. There is no tests yet, please make breif review for these changes. Thanks!

2017-04-20 21:01 UTC, mmamedov commented
Hi @spotman, cool changes thanks! But it is too much of code changes, and I will need more time to digest it. My suggestion is to make it in small steps. In that way it will be easier to test and safe to merge. 

**Let's divide it into small steps.** How about you add new classes for PSR-16, and loggers, without changing any existing code? Push a new branch (or edit current, as you wish) with only these changes, and I will merge it under "**v2.0-dev**" branch

**So it would be the following classes - CachItem/Interface, FileSystemCacheAdapter, DefaultLogger, Exception classes, and composer.json.** 

On the top of each new file please add comments following the current template, with your name (it should be first line, before namespaces). No need to change years on files that were created last year, let it stay for visibility.

Once you do this I can merge it fast, and we can continue refactoring. 
I like where we are going with this, I think it will be great!

2017-04-20 21:17 UTC, mmamedov commented on README.md
> +- getFilepath():string - Get full path for current page's filename. At this point file itself might or might not have been created.
Let's not change this. Filepath are two separate words, let's keep it getFilePath

2017-04-20 21:17 UTC, mmamedov commented on examples/demo-api.php
> +echo 'Cache filepath, getFilepath(): ' . $cache->getFilePath() . '<br/>';
idem

2017-04-20 21:18 UTC, mmamedov commented on src/Storage/FileSystem/FileSystem.php
> +namespace PageCache\Storage\FileSystem;
This should have stayed where it was, after comments block

2017-04-20 21:19 UTC, mmamedov commented on src/Storage/FileSystem/FileSystem.php
> +        if ($this->file_lock === null) {
Do we need to do this? empty() covers it already.

2017-04-20 21:19 UTC, mmamedov commented on src/Storage/FileSystem/FileSystem.php
> +            throw new PageCacheException(__CLASS__ . ' file lock can not be empty');
Nice job with PageCacheException!

2017-04-20 21:20 UTC, mmamedov commented on src/Storage/FileSystem/HashDirectory.php
> +namespace PageCache\Storage\FileSystem;
Let's keep it as it was, after comments.

2017-04-20 21:21 UTC, mmamedov commented on src/Storage/FileSystem/HashDirectory.php
> +        if ($dir) {
!empty() is prefered here, make it more readable.

2017-04-20 21:22 UTC, mmamedov commented on src/Strategy/MobileStrategy.php
> +        if ($mobileDetect !== null) {
During refactoring we can replace whole if block with:
`$this->MobileDetect = $mobileDetect ?: new \Mobile_Detect;
`

2017-04-20 21:23 UTC, mmamedov requested changes
As we discussed, let's split these changes into smaller chunks.

2017-04-21 08:03 UTC, spotman commented on src/Storage/FileSystem/FileSystem.php
> +        if ($this->file_lock === null) {
I use "Php Inspections (EA extended)" plugin for PhpStorm, it recommends to replace "empty" with null check. https://github.com/kalessil/phpinspectionsea/blob/master/docs/types-compatibility.md#empty-usage Also I've read some years ago that null check is much faster. I may change it back, up to you.

2017-04-21 08:14 UTC, spotman commented on README.md
> +- getFilepath():string - Get full path for current page's filename. At this point file itself might or might not have been created.
Hmm, it's refactoring bug probably coz PageCache has method `getFilePath` with capital `P`. I'll change this line in readme.

2017-04-21 08:47 UTC, spotman commented
Hi @mmamedov!

PSR cache implementation would affect all of these files except `HttpHeader(s)` and `DefaultLogger`. Also methods `PageCache::getFile()` and `PageCache::getFilePath()` would be deprecated cos no direct file access would be allowed via PSR-16 cache interface. So I think that splitting would not have any valuable effect coz implementing PSR interfaces needs a huge changes already. I may extract feature for headers forwarding and Expires header but it is also relatively small change. As said in PM, I've tested all of these changes "by hands" and everything worked. I agree with you that it needs more testing and unittests may be written for these new cases. There is an [integration tests suite for PSR-16 providers](https://github.com/matthiasmullie/psr16-integration-tests)  so we may use it for testing `FileSystemCacheAdapter` and underlying classes like `PageCache\Storage\FileSystem\FileSystem`. Any other classes still need to be tested and I may write tests for them if you agree with overall class structure.

2017-05-14 21:36 UTC, merged